--Validation check and quarantine table INSERT for SF_HOUSING_STOCK
INSERT INTO RES_HOUSING.SILVER.QUARANTINE_SF_HOUSING_STOCK (
    PARCL_ID,
    DATE,
    SINGLE_FAMILY,
    CONDO,
    TOWNHOUSE,
    OTHER,
    ALL_PROPERTIES,
    LOAD_TIMESTAMP,
    SOURCE,
    FAILURE_REASON,
    QUARANTINE_TIMESTAMP
)

SELECT
    PARCL_ID,
    DATE,
    SINGLE_FAMILY,
    CONDO,
    TOWNHOUSE,
    OTHER,
    ALL_PROPERTIES,
    LOAD_TIMESTAMP,
    SOURCE,

    CASE
        WHEN PARCL_ID IS NULL
            THEN 'Missing PARCL_ID'
        WHEN DATE IS NULL
            THEN 'Missing DATE'
        WHEN SINGLE_FAMILY < 0
          OR CONDO < 0
          OR TOWNHOUSE < 0
          OR OTHER < 0
          OR ALL_PROPERTIES < 0
            THEN 'Negative housing count'
        WHEN SINGLE_FAMILY + CONDO + TOWNHOUSE + OTHER
             <> ALL_PROPERTIES
            THEN 'Property counts do not reconcile'
    END AS FAILURE_REASON,

    CURRENT_TIMESTAMP()

FROM RES_HOUSING.BRONZE.RAW_SF_HOUSING_STOCK

WHERE
       PARCL_ID IS NULL
    OR DATE IS NULL
    OR SINGLE_FAMILY < 0
    OR CONDO < 0
    OR TOWNHOUSE < 0
    OR OTHER < 0
    OR ALL_PROPERTIES < 0
    OR SINGLE_FAMILY + CONDO + TOWNHOUSE + OTHER
       <> ALL_PROPERTIES;


--Validation check and quarantine table INSERT for SF_PORTFOLIO_STOCK
INSERT INTO RES_HOUSING.SILVER.QUARANTINE_SF_PORTFOLIO_STOCK (
    PARCL_ID,
    DATE,
    COUNT_PORTFOLIO_2_TO_9,
    COUNT_PORTFOLIO_10_TO_99,
    COUNT_PORTFOLIO_100_TO_999,
    COUNT_PORTFOLIO_1000_PLUS,
    COUNT_ALL_PORTFOLIOS,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
    PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
    LOAD_TIMESTAMP,
    SOURCE,
    FAILURE_REASON,
    QUARANTINE_TIMESTAMP
)
SELECT
    *,
    CASE
        WHEN PARCL_ID IS NULL THEN 'Missing PARCL_ID'
        WHEN DATE IS NULL THEN 'Missing DATE'

        WHEN COUNT_PORTFOLIO_2_TO_9 < 0
          OR COUNT_PORTFOLIO_10_TO_99 < 0
          OR COUNT_PORTFOLIO_100_TO_999 < 0
          OR COUNT_PORTFOLIO_1000_PLUS < 0
          OR COUNT_ALL_PORTFOLIOS < 0
            THEN 'Negative portfolio count'

        WHEN COUNT_PORTFOLIO_2_TO_9
           + COUNT_PORTFOLIO_10_TO_99
           + COUNT_PORTFOLIO_100_TO_999
           + COUNT_PORTFOLIO_1000_PLUS
           <> COUNT_ALL_PORTFOLIOS
            THEN 'Portfolio counts do not reconcile'

        WHEN PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9 NOT BETWEEN 0 AND 100
          OR PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99 NOT BETWEEN 0 AND 100
          OR PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999 NOT BETWEEN 0 AND 100
          OR PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS NOT BETWEEN 0 AND 100
          OR PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS NOT BETWEEN 0 AND 100
            THEN 'Invalid percentage'

        ELSE 'Unknown validation failure'
    END AS FAILURE_REASON,

    CURRENT_TIMESTAMP() AS QUARANTINE_TIMESTAMP

FROM RES_HOUSING.BRONZE.RAW_SF_PORTFOLIO_STOCK
WHERE PARCL_ID IS NULL
   OR DATE IS NULL
   OR COUNT_PORTFOLIO_2_TO_9 < 0
   OR COUNT_PORTFOLIO_10_TO_99 < 0
   OR COUNT_PORTFOLIO_100_TO_999 < 0
   OR COUNT_PORTFOLIO_1000_PLUS < 0
   OR COUNT_ALL_PORTFOLIOS < 0
   OR COUNT_PORTFOLIO_2_TO_9
    + COUNT_PORTFOLIO_10_TO_99
    + COUNT_PORTFOLIO_100_TO_999
    + COUNT_PORTFOLIO_1000_PLUS
    <> COUNT_ALL_PORTFOLIOS
   OR PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9 NOT BETWEEN 0 AND 100
   OR PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99 NOT BETWEEN 0 AND 100
   OR PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999 NOT BETWEEN 0 AND 100
   OR PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS NOT BETWEEN 0 AND 100
   OR PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS NOT BETWEEN 0 AND 100;


--Validation check and quarantine table INSERT for SF_HOUSING_EVENTS
INSERT INTO RES_HOUSING.SILVER.QUARANTINE_SF_HOUSING_EVENTS (
    PARCL_ID,
    DATE,
    ACQUISITIONS,
    DISPOSITIONS,
    NEW_LISTINGS_FOR_SALE,
    NEW_RENTAL_LISTINGS,
    TRANSFERS,
    PORTFOLIO_SIZE,
    LOAD_TIMESTAMP,
    SOURCE,
    FAILURE_REASON,
    QUARANTINE_TIMESTAMP
)
SELECT
    *,
    CASE
        WHEN PARCL_ID IS NULL THEN 'Missing PARCL_ID'
        WHEN DATE IS NULL THEN 'Missing DATE'
        WHEN PORTFOLIO_SIZE IS NULL THEN 'Missing PORTFOLIO_SIZE'

        WHEN PORTFOLIO_SIZE NOT IN (
            'PORTFOLIO_2_TO_9',
            'PORTFOLIO_10_TO_99',
            'PORTFOLIO_100_TO_999',
            'PORTFOLIO_1000_PLUS'
        )
            THEN 'Invalid portfolio category'

        WHEN ACQUISITIONS < 0
          OR DISPOSITIONS < 0
          OR NEW_LISTINGS_FOR_SALE < 0
          OR NEW_RENTAL_LISTINGS < 0
          OR TRANSFERS < 0
            THEN 'Negative event count'

        ELSE 'Unknown validation failure'
    END AS FAILURE_REASON,

    CURRENT_TIMESTAMP() AS QUARANTINE_TIMESTAMP

FROM RES_HOUSING.BRONZE.RAW_SF_HOUSING_EVENTS
WHERE PARCL_ID IS NULL
   OR DATE IS NULL
   OR PORTFOLIO_SIZE IS NULL
   OR PORTFOLIO_SIZE NOT IN (
        'PORTFOLIO_2_TO_9',
        'PORTFOLIO_10_TO_99',
        'PORTFOLIO_100_TO_999',
        'PORTFOLIO_1000_PLUS'
   )
   OR ACQUISITIONS < 0
   OR DISPOSITIONS < 0
   OR NEW_LISTINGS_FOR_SALE < 0
   OR NEW_RENTAL_LISTINGS < 0
   OR TRANSFERS < 0;