-- ============================================================
-- SF HOUSING STOCK
-- ============================================================

MERGE INTO RES_HOUSING.BRONZE.RAW_SF_HOUSING_STOCK AS target
USING RES_HOUSING.BRONZE.STAGING_RAW_SF_HOUSING_STOCK AS source
    ON target.PARCL_ID = source.PARCL_ID
   AND target.DATE = source.DATE

WHEN MATCHED THEN
    UPDATE SET
        target.SINGLE_FAMILY = source.SINGLE_FAMILY,
        target.CONDO = source.CONDO,
        target.TOWNHOUSE = source.TOWNHOUSE,
        target.OTHER = source.OTHER,
        target.ALL_PROPERTIES = source.ALL_PROPERTIES,
        target.LOAD_TIMESTAMP = source.LOAD_TIMESTAMP,
        target.SOURCE = source.SOURCE

WHEN NOT MATCHED THEN
    INSERT (
        PARCL_ID,
        DATE,
        SINGLE_FAMILY,
        CONDO,
        TOWNHOUSE,
        OTHER,
        ALL_PROPERTIES,
        LOAD_TIMESTAMP,
        SOURCE
    )
    VALUES (
        source.PARCL_ID,
        source.DATE,
        source.SINGLE_FAMILY,
        source.CONDO,
        source.TOWNHOUSE,
        source.OTHER,
        source.ALL_PROPERTIES,
        source.LOAD_TIMESTAMP,
        source.SOURCE
    );

UPDATE RES_HOUSING.CONTROL.WATERMARKS
SET LAST_WATERMARK = (
    SELECT MAX(DATE)
    FROM RES_HOUSING.BRONZE.STAGING_RAW_SF_HOUSING_STOCK
)
WHERE SCHEMA_NAME = 'BRONZE'
  AND TABLE_NAME = 'RAW_SF_HOUSING_STOCK'
  AND DATE_KEY = 'DATE';


-- ============================================================
-- SF PORTFOLIO STOCK
-- ============================================================

MERGE INTO RES_HOUSING.BRONZE.RAW_SF_PORTFOLIO_STOCK AS target
USING RES_HOUSING.BRONZE.STAGING_RAW_SF_PORTFOLIO_STOCK AS source
    ON target.PARCL_ID = source.PARCL_ID
   AND target.DATE = source.DATE

WHEN MATCHED THEN
    UPDATE SET
        target.COUNT_PORTFOLIO_2_TO_9 = source.COUNT_PORTFOLIO_2_TO_9,
        target.COUNT_PORTFOLIO_10_TO_99 = source.COUNT_PORTFOLIO_10_TO_99,
        target.COUNT_PORTFOLIO_100_TO_999 = source.COUNT_PORTFOLIO_100_TO_999,
        target.COUNT_PORTFOLIO_1000_PLUS = source.COUNT_PORTFOLIO_1000_PLUS,
        target.COUNT_ALL_PORTFOLIOS = source.COUNT_ALL_PORTFOLIOS,
        target.PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9 =
            source.PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
        target.PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99 =
            source.PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
        target.PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999 =
            source.PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
        target.PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS =
            source.PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
        target.PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS =
            source.PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
        target.LOAD_TIMESTAMP = source.LOAD_TIMESTAMP,
        target.SOURCE = source.SOURCE

WHEN NOT MATCHED THEN
    INSERT (
        PARCL_ID,
        DATE,
        COUNT_PORTFOLIO_2_TO_9,
        COUNT_PORTFOLIO_10_TO_99,
        COUNT_PORTFOLIO_100_TO_999,
        COUNT_PORTFOLIO_1000_PLUS,
        COUNT_ALL_PORTFOLIOS,
        PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
        PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
        PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
        PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
        PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
        LOAD_TIMESTAMP,
        SOURCE
    )
    VALUES (
        source.PARCL_ID,
        source.DATE,
        source.COUNT_PORTFOLIO_2_TO_9,
        source.COUNT_PORTFOLIO_10_TO_99,
        source.COUNT_PORTFOLIO_100_TO_999,
        source.COUNT_PORTFOLIO_1000_PLUS,
        source.COUNT_ALL_PORTFOLIOS,
        source.PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
        source.PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
        source.PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
        source.PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
        source.PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
        source.LOAD_TIMESTAMP,
        source.SOURCE
    );

UPDATE RES_HOUSING.CONTROL.WATERMARKS
SET LAST_WATERMARK = (
    SELECT MAX(DATE)
    FROM RES_HOUSING.BRONZE.STAGING_RAW_SF_PORTFOLIO_STOCK
)
WHERE SCHEMA_NAME = 'BRONZE'
  AND TABLE_NAME = 'RAW_SF_PORTFOLIO_STOCK'
  AND DATE_KEY = 'DATE';

-- ============================================================
-- SF HOUSING EVENTS
-- ============================================================

MERGE INTO RES_HOUSING.BRONZE.RAW_SF_HOUSING_EVENTS AS target
USING RES_HOUSING.BRONZE.STAGING_RAW_SF_HOUSING_EVENTS AS source
    ON target.PARCL_ID = source.PARCL_ID
   AND target.DATE = source.DATE
   AND target.PORTFOLIO_SIZE = source.PORTFOLIO_SIZE

WHEN MATCHED THEN
    UPDATE SET
        target.ACQUISITIONS = source.ACQUISITIONS,
        target.DISPOSITIONS = source.DISPOSITIONS,
        target.NEW_LISTINGS_FOR_SALE = source.NEW_LISTINGS_FOR_SALE,
        target.NEW_RENTAL_LISTINGS = source.NEW_RENTAL_LISTINGS,
        target.TRANSFERS = source.TRANSFERS,
        target.LOAD_TIMESTAMP = source.LOAD_TIMESTAMP,
        target.SOURCE = source.SOURCE

WHEN NOT MATCHED THEN
    INSERT (
        PARCL_ID,
        DATE,
        ACQUISITIONS,
        DISPOSITIONS,
        NEW_LISTINGS_FOR_SALE,
        NEW_RENTAL_LISTINGS,
        TRANSFERS,
        PORTFOLIO_SIZE,
        LOAD_TIMESTAMP,
        SOURCE
    )
    VALUES (
        source.PARCL_ID,
        source.DATE,
        source.ACQUISITIONS,
        source.DISPOSITIONS,
        source.NEW_LISTINGS_FOR_SALE,
        source.NEW_RENTAL_LISTINGS,
        source.TRANSFERS,
        source.PORTFOLIO_SIZE,
        source.LOAD_TIMESTAMP,
        source.SOURCE
    );

UPDATE RES_HOUSING.CONTROL.WATERMARKS
SET LAST_WATERMARK = (
    SELECT MAX(DATE)
    FROM RES_HOUSING.BRONZE.STAGING_RAW_SF_HOUSING_EVENTS
)
WHERE SCHEMA_NAME = 'BRONZE'
  AND TABLE_NAME = 'RAW_SF_HOUSING_EVENTS'
  AND DATE_KEY = 'DATE';