--Essentially performs integrity checks AND deduplicates keys by choosing latest load_timstamp value
INSERT INTO RES_HOUSING.SILVER.SF_HOUSING_STOCK (
    PARCL_ID,
    DATE,
    SINGLE_FAMILY,
    CONDO,
    TOWNHOUSE,
    OTHER,
    ALL_PROPERTIES,
    LOAD_TIMESTAMP,
    SOURCE
)

SELECT
    PARCL_ID,
    DATE,
    SINGLE_FAMILY,
    CONDO,
    TOWNHOUSE,
    OTHER,
    ALL_PROPERTIES,
    LOAD_TIMESTAMP,
    SOURCE

FROM RES_HOUSING.BRONZE.RAW_SF_HOUSING_STOCK

WHERE PARCL_ID IS NOT NULL
  AND DATE IS NOT NULL

  -- Counts cannot be negative
  AND SINGLE_FAMILY >= 0
  AND CONDO >= 0
  AND TOWNHOUSE >= 0
  AND OTHER >= 0
  AND ALL_PROPERTIES >= 0

  -- Component counts must reconcile
  AND SINGLE_FAMILY
      + CONDO
      + TOWNHOUSE
      + OTHER
      = ALL_PROPERTIES

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PARCL_ID, DATE
    ORDER BY LOAD_TIMESTAMP DESC
) = 1;




INSERT INTO RES_HOUSING.SILVER.SF_PORTFOLIO_STOCK (
    PARCL_ID,
    DATE,
    COUNT_PORTFOLIO_2_TO_9,
    COUNT_PORTFOLIO_10_TO_99,
    COUNT_PORTFOLIO_100_TO_999,
    COUNT_PORTFOLIO_1000_PLUS,
    COUNT_ALL_PORTFOLIOS,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
    PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
    LOAD_TIMESTAMP,
    SOURCE
)

SELECT
    PARCL_ID,
    DATE,
    COUNT_PORTFOLIO_2_TO_9,
    COUNT_PORTFOLIO_10_TO_99,
    COUNT_PORTFOLIO_100_TO_999,
    COUNT_PORTFOLIO_1000_PLUS,
    COUNT_ALL_PORTFOLIOS,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999,
    PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS,
    PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS,
    LOAD_TIMESTAMP,
    SOURCE

FROM RES_HOUSING.BRONZE.RAW_SF_PORTFOLIO_STOCK

WHERE PARCL_ID IS NOT NULL
  AND DATE IS NOT NULL

  -- Portfolio counts cannot be negative
  AND COUNT_PORTFOLIO_2_TO_9 >= 0
  AND COUNT_PORTFOLIO_10_TO_99 >= 0
  AND COUNT_PORTFOLIO_100_TO_999 >= 0
  AND COUNT_PORTFOLIO_1000_PLUS >= 0
  AND COUNT_ALL_PORTFOLIOS >= 0

  -- Portfolio components must reconcile
  AND COUNT_PORTFOLIO_2_TO_9
      + COUNT_PORTFOLIO_10_TO_99
      + COUNT_PORTFOLIO_100_TO_999
      + COUNT_PORTFOLIO_1000_PLUS
      = COUNT_ALL_PORTFOLIOS

  -- Percentages must be valid
  AND PCT_SF_HOUSING_STOCK_PORTFOLIO_2_TO_9 BETWEEN 0 AND 100
  AND PCT_SF_HOUSING_STOCK_PORTFOLIO_10_TO_99 BETWEEN 0 AND 100
  AND PCT_SF_HOUSING_STOCK_PORTFOLIO_100_TO_999 BETWEEN 0 AND 100
  AND PCT_SF_HOUSING_STOCK_PORTFOLIO_1000_PLUS BETWEEN 0 AND 100
  AND PCT_SF_HOUSING_STOCK_ALL_PORTFOLIOS BETWEEN 0 AND 100

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PARCL_ID, DATE
    ORDER BY LOAD_TIMESTAMP DESC
) = 1;



INSERT INTO RES_HOUSING.SILVER.SF_HOUSING_EVENTS (
    PARCL_ID,
    DATE,
    ACQUISITIONS,
    DISPOSITIONS,
    NEW_LISTINGS_FOR_SALE,
    NEW_RENTAL_LISTINGS,
    TRANSFERS,
    PORTFOLIO_SIZE,
    LOAD_TIMESTAMP,
    SOURCE
)

SELECT
    PARCL_ID,
    DATE,
    ACQUISITIONS,
    DISPOSITIONS,
    NEW_LISTINGS_FOR_SALE,
    NEW_RENTAL_LISTINGS,
    TRANSFERS,
    PORTFOLIO_SIZE,
    LOAD_TIMESTAMP,
    SOURCE

FROM RES_HOUSING.BRONZE.RAW_SF_HOUSING_EVENTS

WHERE PARCL_ID IS NOT NULL
  AND DATE IS NOT NULL
  AND PORTFOLIO_SIZE IS NOT NULL

  -- Only expected portfolio categories
  AND PORTFOLIO_SIZE IN (
      'PORTFOLIO_2_TO_9',
      'PORTFOLIO_10_TO_99',
      'PORTFOLIO_100_TO_999',
      'PORTFOLIO_1000_PLUS'
  )

  -- Event counts cannot be negative
  AND ACQUISITIONS >= 0
  AND DISPOSITIONS >= 0
  AND NEW_LISTINGS_FOR_SALE >= 0
  AND NEW_RENTAL_LISTINGS >= 0
  AND TRANSFERS >= 0

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PARCL_ID, DATE, PORTFOLIO_SIZE
    ORDER BY LOAD_TIMESTAMP DESC
) = 1;